Add attribute fastcall to derived class member JSImageConstructor::construct
Otherwise the Debian build on i386 fails with this error:
In file included from ../Source/WebCore/bindings/js/JSImageConstructor.cpp:24,
                 from ../Source/WebCore/bindings/js/JSBindingsAllInOne.cpp:101:
../Source/WebCore/bindings/js/JSDOMConstructor.h: In instantiation of ‘static JSC::ConstructType WebCore::JSDOMNamedConstructor<JSClass>::getConstructData(JSC::JSCell*, JSC::ConstructData&) [with JSClass = WebCore::JSHTMLImageElement]’:
../Source/WebCore/bindings/js/JSImageConstructor.cpp:75:97:   required from here
../Source/WebCore/bindings/js/JSDOMConstructor.h:195:35: error: invalid conversion from ‘JSC::EncodedJSValue (*)(JSC::ExecState*)’ {aka ‘long long int (*)(JSC::ExecState*)’} to ‘JSC::NativeFunction’ {aka ‘long long int (__attribute__((fastcall)) *)(JSC::ExecState*)’} [-fpermissive]
     constructData.native.function = construct;
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~